"""baseline_schema

Revision ID: d05180aff149
Revises: 
Create Date: 2026-05-16 09:46:35.093505+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05180aff149'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('IN', 'OUT', name='categorytype'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('npwp', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('letterhead_url', sa.String(length=500), nullable=True),
    sa.Column('director_name', sa.String(length=120), nullable=True),
    sa.Column('bank_account', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)

    op.create_table('funders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funders'))
    )
    with op.batch_alter_table('funders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funders_name'), ['name'], unique=True)

    op.create_table('messaging_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messaging_config'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('SUPERADMIN', 'CENTRAL_ADMIN', 'PROJECT_ADMIN', 'EXECUTIVE', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('scope_all_projects', sa.Boolean(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=40), nullable=True),
    sa.Column('whatsapp_chat_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_chat_id', name=op.f('uq_users_telegram_chat_id')),
    sa.UniqueConstraint('whatsapp_chat_id', name=op.f('uq_users_whatsapp_chat_id'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vendors_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('VENDOR', 'CLIENT', 'BOTH', name='vendorclienttype'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('npwp', sa.String(length=40), nullable=True),
    sa.Column('contact', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('bank_account', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors_clients'))
    )
    with op.batch_alter_table('vendors_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_clients_name'), ['name'], unique=False)

    op.create_table('ai_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DONE', 'FAILED', 'REVIEWED', name='aiextractionstatus'), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_ai_extractions_reviewed_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_extractions'))
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('group_key', sa.String(length=40), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_app_settings_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_group_key'), ['group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'SUBMIT', 'VERIFY', 'CANCEL', 'APPROVE', 'REJECT', name='auditaction'), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_user_id', ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('pic_user_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('MENUNGGU_PERSETUJUAN', 'AKTIF', 'SELESAI', 'DITAHAN', 'DIBATALKAN', name='projectstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('project_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('overbudget_tolerance_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_ppn_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_pph_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('marketing_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('proposed_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_projects_approved_by_id_users')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_projects_company_id_companies')),
    sa.ForeignKeyConstraint(['pic_user_id'], ['users.id'], name=op.f('fk_projects_pic_user_id_users')),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], name=op.f('fk_projects_proposed_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)

    op.create_table('role_menu_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SUPERADMIN', 'CENTRAL_ADMIN', 'PROJECT_ADMIN', 'EXECUTIVE', name='userrole'), nullable=False),
    sa.Column('menu_id', sa.String(length=80), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_role_menu_policies_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_menu_policies')),
    sa.UniqueConstraint('role', 'menu_id', name='uq_role_menu')
    )
    with op.batch_alter_table('role_menu_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_menu_policies_menu_id'), ['menu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_menu_policies_role'), ['role'], unique=False)

    op.create_table('telegram_link_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_link_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_link_codes'))
    )
    with op.batch_alter_table('telegram_link_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_link_codes_code'), ['code'], unique=True)

    op.create_table('whatsapp_link_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_whatsapp_link_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_link_codes'))
    )
    with op.batch_alter_table('whatsapp_link_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_link_codes_code'), ['code'], unique=True)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IN', 'OUT', name='invoicetype'), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('vendor_client_id', sa.Integer(), nullable=True),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_invoices_created_by_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_invoices_project_id_projects')),
    sa.ForeignKeyConstraint(['vendor_client_id'], ['vendors_clients.id'], name=op.f('fk_invoices_vendor_client_id_vendors_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoices_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_invoices_due_date', ['due_date'], unique=False)
        batch_op.create_index('ix_invoices_invoice_date', ['invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_invoices_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_vendor_client_id'), ['vendor_client_id'], unique=False)

    op.create_table('project_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('doc_type', sa.String(length=40), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_attachments_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_project_attachments_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_attachments'))
    )
    op.create_table('project_funders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('funder_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['funder_id'], ['funders.id'], name=op.f('fk_project_funders_funder_id_funders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_funders_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_funders')),
    sa.UniqueConstraint('project_id', 'funder_id', name='uq_project_funder')
    )
    with op.batch_alter_table('project_funders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_funders_funder_id'), ['funder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_funders_project_id'), ['project_id'], unique=False)

    op.create_table('project_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_users_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_users')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_user')
    )
    with op.batch_alter_table('project_users', schema=None) as batch_op:
        batch_op.create_index('ix_project_users_user_id', ['user_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('vendor_client_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=False),
    sa.Column('needed_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'APPROVED', 'PARTIALLY_FULFILLED', 'FULFILLED', 'CANCELLED', name='postatus'), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_purchase_orders_approved_by_id_users')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_purchase_orders_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_purchase_orders_created_by_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_purchase_orders_project_id_projects')),
    sa.ForeignKeyConstraint(['vendor_client_id'], ['vendors_clients.id'], name=op.f('fk_purchase_orders_vendor_client_id_vendors_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders'))
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index('ix_po_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_po_po_date', ['po_date'], unique=False)
        batch_op.create_index('ix_po_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_vendor_client_id'), ['vendor_client_id'], unique=False)

    op.create_table('invoice_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_attachments_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_invoice_attachments_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_attachments'))
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    op.create_table('po_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_po_items_po_id_purchase_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_po_items'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tx_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('IN', 'OUT', name='txntype'), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('parent_advance_tx_id', sa.Integer(), nullable=True),
    sa.Column('party_type', sa.Enum('COMPANY', 'PERSONAL', 'EMPLOYEE', 'INTERNAL', 'OTHER', name='partytype'), nullable=True),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('party_id_number', sa.String(length=80), nullable=True),
    sa.Column('party_account', sa.String(length=200), nullable=True),
    sa.Column('vendor_client_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'TRANSFER', 'QRIS', 'GIRO', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('reference_no', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'VERIFIED', 'REJECTED', 'CANCELLED', name='txnstatus'), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_transactions_created_by_id_users')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_transactions_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['parent_advance_tx_id'], ['transactions.id'], name=op.f('fk_transactions_parent_advance_tx_id_transactions')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_transactions_project_id_projects')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_transactions_purchase_order_id_purchase_orders')),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_transactions_recipient_user_id_users')),
    sa.ForeignKeyConstraint(['vendor_client_id'], ['vendors_clients.id'], name=op.f('fk_transactions_vendor_client_id_vendors_clients')),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name=op.f('fk_transactions_verified_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index('ix_transactions_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_transactions_invoice_id', ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_transactions_project_date', ['project_id', 'tx_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_transactions_project_status_type', ['project_id', 'status', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_recipient_user_id'), ['recipient_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tx_date'), ['tx_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)
        batch_op.create_index('ix_transactions_vendor_client', ['vendor_client_id'], unique=False)

    op.create_table('cash_advance_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_advance_tx_id', sa.Integer(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_by_id', sa.Integer(), nullable=False),
    sa.Column('returned_to_kas', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('topup_tx_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cash_advance_tx_id'], ['transactions.id'], name=op.f('fk_cash_advance_settlements_cash_advance_tx_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['settled_by_id'], ['users.id'], name=op.f('fk_cash_advance_settlements_settled_by_id_users')),
    sa.ForeignKeyConstraint(['topup_tx_id'], ['transactions.id'], name=op.f('fk_cash_advance_settlements_topup_tx_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_advance_settlements'))
    )
    with op.batch_alter_table('cash_advance_settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_advance_settlements_cash_advance_tx_id'), ['cash_advance_tx_id'], unique=True)

    op.create_table('invoice_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('allocated_amount > 0', name=op.f('ck_invoice_allocations_ck_alloc_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_invoice_allocations_created_by_id_users')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_allocations_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_invoice_allocations_transaction_id_transactions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_allocations')),
    sa.UniqueConstraint('transaction_id', 'invoice_id', 'deleted_at', name='uq_alloc_pair')
    )
    with op.batch_alter_table('invoice_allocations', schema=None) as batch_op:
        batch_op.create_index('ix_alloc_inv', ['invoice_id'], unique=False)
        batch_op.create_index('ix_alloc_txn', ['transaction_id'], unique=False)

    op.create_table('telegram_pending_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=40), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_telegram_pending_attachments_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_pending_attachments'))
    )
    with op.batch_alter_table('telegram_pending_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_pending_attachments_chat_id'), ['chat_id'], unique=False)

    op.create_table('transaction_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_attachments_transaction_id_transactions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_transaction_attachments_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_attachments'))
    )
    op.create_table('transaction_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transaction_items_category_id_categories')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_items_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_items'))
    )
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_items_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('whatsapp_pending_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_whatsapp_pending_attachments_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_pending_attachments'))
    )
    with op.batch_alter_table('whatsapp_pending_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_pending_attachments_chat_id'), ['chat_id'], unique=False)

    op.create_table('cash_advance_settlement_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_cash_advance_settlement_items_category_id_categories')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_cash_advance_settlement_items_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['settlement_id'], ['cash_advance_settlements.id'], name=op.f('fk_cash_advance_settlement_items_settlement_id_cash_advance_settlements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_advance_settlement_items'))
    )
    with op.batch_alter_table('cash_advance_settlement_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_advance_settlement_items_settlement_id'), ['settlement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_advance_settlement_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_advance_settlement_items_settlement_id'))

    op.drop_table('cash_advance_settlement_items')
    with op.batch_alter_table('whatsapp_pending_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_pending_attachments_chat_id'))

    op.drop_table('whatsapp_pending_attachments')
    with op.batch_alter_table('transaction_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_items_transaction_id'))

    op.drop_table('transaction_items')
    op.drop_table('transaction_attachments')
    with op.batch_alter_table('telegram_pending_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_pending_attachments_chat_id'))

    op.drop_table('telegram_pending_attachments')
    with op.batch_alter_table('invoice_allocations', schema=None) as batch_op:
        batch_op.drop_index('ix_alloc_txn')
        batch_op.drop_index('ix_alloc_inv')

    op.drop_table('invoice_allocations')
    with op.batch_alter_table('cash_advance_settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_advance_settlements_cash_advance_tx_id'))

    op.drop_table('cash_advance_settlements')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_vendor_client')
        batch_op.drop_index(batch_op.f('ix_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_tx_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_recipient_user_id'))
        batch_op.drop_index('ix_transactions_project_status_type')
        batch_op.drop_index(batch_op.f('ix_transactions_project_id'))
        batch_op.drop_index('ix_transactions_project_date')
        batch_op.drop_index(batch_op.f('ix_transactions_kind'))
        batch_op.drop_index('ix_transactions_invoice_id')
        batch_op.drop_index('ix_transactions_deleted_at')
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))

    op.drop_table('transactions')
    op.drop_table('po_items')
    op.drop_table('invoice_items')
    op.drop_table('invoice_attachments')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_vendor_client_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_project_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_company_id'))
        batch_op.drop_index('ix_po_project_status')
        batch_op.drop_index('ix_po_po_date')
        batch_op.drop_index('ix_po_deleted_at')

    op.drop_table('purchase_orders')
    with op.batch_alter_table('project_users', schema=None) as batch_op:
        batch_op.drop_index('ix_project_users_user_id')

    op.drop_table('project_users')
    with op.batch_alter_table('project_funders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_funders_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_funders_funder_id'))

    op.drop_table('project_funders')
    op.drop_table('project_attachments')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_vendor_client_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_type'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index('ix_invoices_project_status')
        batch_op.drop_index(batch_op.f('ix_invoices_project_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_number'))
        batch_op.drop_index('ix_invoices_invoice_date')
        batch_op.drop_index('ix_invoices_due_date')
        batch_op.drop_index('ix_invoices_deleted_at')

    op.drop_table('invoices')
    with op.batch_alter_table('whatsapp_link_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_link_codes_code'))

    op.drop_table('whatsapp_link_codes')
    with op.batch_alter_table('telegram_link_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_link_codes_code'))

    op.drop_table('telegram_link_codes')
    with op.batch_alter_table('role_menu_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_menu_policies_role'))
        batch_op.drop_index(batch_op.f('ix_role_menu_policies_menu_id'))

    op.drop_table('role_menu_policies')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_code'))

    op.drop_table('projects')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_id')
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_created_at')

    op.drop_table('audit_logs')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))
        batch_op.drop_index(batch_op.f('ix_app_settings_group_key'))

    op.drop_table('app_settings')
    op.drop_table('ai_extractions')
    with op.batch_alter_table('vendors_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_clients_name'))

    op.drop_table('vendors_clients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('messaging_config')
    with op.batch_alter_table('funders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funders_name'))

    op.drop_table('funders')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_name'))

    op.drop_table('companies')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    # ### end Alembic commands ###
